const Search = document.querySelectorAll('.Search select')


// for (let select of Search) {
//     for (code in DistList) {
//         let newOption = document.createElement('option')
//         newOption.innerText = code
//         newOption.value = code
//         newOption.selected = 'selected'
//         select.append(newOption)
//     }
// }


// input.addEventListener('click', (evt) => {
//     for (let input of Search) {
//         for (code in DistList) {
//             let newOption = document.createElement('option')
//             newOption.innerText = code
//             newOption.value = code
//             newOption.selected = 'selected'
//             select.append(newOption)
//         }
//     }
// })